package model.pojo;
// Generated May 9, 2018 11:04:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int id;
     private Project project;
     private String name;
     private boolean gen;
     private Date birthday;

    public Employee() {
    }

    public Employee(int id, Project project, String name, boolean gen, Date birthday) {
       this.id = id;
       this.project = project;
       this.name = name;
       this.gen = gen;
       this.birthday = birthday;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isGen() {
        return this.gen;
    }
    
    public void setGen(boolean gen) {
        this.gen = gen;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }




}


